
server:
  port: 8081
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: miu.alumni.management.portal@gmail.com
    password: fvmerzybvaodqklj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gid
email:
  from-address: miu.alumni.management.portal@gmail.com


